name: linux_musl

on:
  pull_request:
    types: [ open, reopen, synchronize ]
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  cleanup:
    runs-on: [ self-hosted, linux-do ]
    container: grafin1992/nemu-ci:v1.2
    steps:
      - name: Clean workspace
        run: rm -rf nemu_musl

  clone:
    runs-on: [ self-hosted, linux-do ]
    container: grafin1992/nemu-ci:v1.2
    needs: cleanup

    steps:
      - name: Get nEMU sources
        run: git clone --depth 1 https://github.com/nemuTUI/nemu nemu_musl

  configure:
    runs-on: [ self-hosted, linux-do ]
    container: grafin1992/nemu-ci:v1.2
    needs: clone

    steps:
      - name: Configure nEMU build
        working-directory: ./nemu_musl
        run: |
          mkdir build && cd build
          cmake -G Ninja ../ \
            -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON

  build:
    runs-on: [ self-hosted, linux-do ]
    container: grafin1992/nemu-ci:v1.2
    needs: configure

    steps:
      - name: Build nEMU
        working-directory: ./nemu_musl/build
        run: ninja
