name: linux_musl

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  musl_build:
    runs-on: [ self-hosted, linux-do ]
    container: voidso/nemu-musl-ci:v1.1

    steps:
      - name: Get nEMU sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure nEMU build
        run: |
          cmake -G Ninja \
            -DNM_WITH_NETWORK_MAP=ON -DNM_WITH_DBUS=ON -DNM_WITH_REMOTE=ON

      - name: Build nEMU
        run: cmake --build .
